AWSTemplateFormatVersion: "2010-09-09"
Description: Infra stack for Registrar lab (VPC + private subnets + SGs + RDS Postgres)

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.30.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.30.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: false

  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.30.2.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: false

  LambdaSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda SG for Registrar app
      VpcId: !Ref Vpc

  DbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Postgres SG (allow 5432 from Lambda SG only)
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSg

  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS Postgres
      SubnetIds: [!Ref SubnetA, !Ref SubnetB]

  DbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp2
      PubliclyAccessible: false
      MultiAZ: false
      DBName: appdb
      MasterUsername: postgres
      MasterUserPassword: PostgresPass123!
      VPCSecurityGroups: [!Ref DbSg]
      DBSubnetGroupName: !Ref DbSubnetGroup
      BackupRetentionPeriod: 0
      DeleteAutomatedBackups: true
      DeletionProtection: false

Outputs:
  VpcId:
    Value: !Ref Vpc
    Export:
      Name: Registrar-VpcId

  SubnetAId:
    Value: !Ref SubnetA
    Export:
      Name: Registrar-SubnetAId

  SubnetBId:
    Value: !Ref SubnetB
    Export:
      Name: Registrar-SubnetBId

  LambdaSgId:
    Value: !Ref LambdaSg
    Export:
      Name: Registrar-LambdaSgId

  DbHost:
    Value: !GetAtt DbInstance.Endpoint.Address
    Export:
      Name: Registrar-DbHost

  DbPort:
    Value: !GetAtt DbInstance.Endpoint.Port
    Export:
      Name: Registrar-DbPort

  DbName:
    Value: appdb
    Export:
      Name: Registrar-DbName

  DbUser:
    Value: postgres
    Export:
      Name: Registrar-DbUser

  DbPass:
    Value: PostgresPass123!
    Export:
      Name: Registrar-DbPass
