AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Registrar App stack (API Gateway + Lambda in VPC + RDS Postgres)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 128

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  PsycopgLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: registrar-psycopg-layer
      ContentUri: layer/
      CompatibleRuntimes: [python3.12]
    Metadata:
      BuildMethod: python3.12

  InitSchemaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.init_schema_handler
      CodeUri: src/
      Layers: [!Ref PsycopgLayer]
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SecurityGroupIds: [!ImportValue Registrar-LambdaSgId]
        SubnetIds:
          - !ImportValue Registrar-SubnetAId
          - !ImportValue Registrar-SubnetBId
      Environment:
        Variables:
          DB_HOST: !ImportValue Registrar-DbHost
          DB_PORT: !ImportValue Registrar-DbPort
          DB_NAME: !ImportValue Registrar-DbName
          DB_USER: !ImportValue Registrar-DbUser
          DB_PASS: !ImportValue Registrar-DbPass

  InitSchema:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt InitSchemaFunction.Arn

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.register_handler
      CodeUri: src/
      Layers: [!Ref PsycopgLayer]
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SecurityGroupIds: [!ImportValue Registrar-LambdaSgId]
        SubnetIds:
          - !ImportValue Registrar-SubnetAId
          - !ImportValue Registrar-SubnetBId
      Environment:
        Variables:
          DB_HOST: !ImportValue Registrar-DbHost
          DB_PORT: !ImportValue Registrar-DbPort
          DB_NAME: !ImportValue Registrar-DbName
          DB_USER: !ImportValue Registrar-DbUser
          DB_PASS: !ImportValue Registrar-DbPass
      Events:
        Register:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /register
            Method: POST

Outputs:
  ApiBaseUrl:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod"
